apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: frontend
    newName: gitlab.lnu.se:5050/2dv013/student/team-2024-04-snorlax/litter-mono/frontend
    newTag: staging-latest
patchesStrategicMerge:
  - ./ingress-patch.yaml
  - ./litter-service-patch.yaml
  - ./deployment-patch.yaml
