# frontend/overlays/staging

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: frontend
    newName: gitlab.lnu.se:5050/2dv013/student/team-2024-04-snorlax/litter-mono/frontend
    newTag: staging-latest
patches:
 - patch: |
      - op: add
        path: /spec/ingressClassName
        value: nginx
      - op: replace
        path: /metadata/namespace
        value: ingress-system
   target:
    kind: Ingress

 - path: ./deployment-patch.yaml
   target:
    kind: Deployment
  # NOTE - JSON patch is required to change teh name of the service.
 - patch: |
      - op: replace
        path: /metadata/name
        value: litter-staging
   target:
     kind: Service
