apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: litter-web-app
manifests:      # Add default manifest config
  kustomize:
    paths: 
      - k8s/overlays/staging
deploy:
  kubectl: {}

profiles:
  - name: production
    manifests:
      kustomize:
        paths:
          - k8s/overlays/production  # Points to central overlay
  - name: dev
    build:
      artifacts:
        - image: frontend
          docker:
            dockerfile: Dockerfile.production
          context: ./frontend
    manifests:
      rawYaml:  # Use raw yaml for local dev
        - frontend/k8s/base/litter.yaml
        - frontend/k8s/base/ingress.production.yaml
  - name: staging
    manifests:
      kustomize:
        paths: 
          - k8s/overlays/staging
