apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: litter-web-app
build:
  artifacts:
    - image: frontend
      docker:
        dockerfile: Dockerfile.production
      context: ./frontend
manifests:
  rawYaml:
    - ./frontend/k8s/litter.yaml
    - ./frontend/k8s/ingress.production.yaml
deploy:
  kubectl: {}
  
profiles:
  - name: production
    build:
      artifacts:
        - image: gitlab.lnu.se:5050/2dv013/student/team-2024-04-snorlax/litter-mono/frontend
          docker:
            dockerfile: ./frontend/Dockerfile.production
          context: ./frontend
    patches:
     - op: replace
       path: /manifests/rawYaml/*/metadata/namespace
       value: production
     - op: replace
       path: /manifests/rawYaml/0/spec/template/spec/containers/0/image
       value: gitlab.lnu.se:5050/2dv013/student/team-2024-04-snorlax/litter-mono/frontend
     - op: add
       path: /manifests/rawYaml/1/spec/ingressClassName
       value: nginx

  - name: staging
    build:
      artifacts:
        - image: gitlab.lnu.se:5050/2dv013/student/team-2024-04-snorlax/litter-mono/staging-frontend
          docker:
            dockerfile: ./frontend/Dockerfile.production
          context: ./frontend
    patches:
      - op: replace
        path: /manifests/rawYaml/*/metadata/namespace
        value: staging
      - op: replace
        path: /manifests/rawYaml/0/spec/template/spec/containers/0/image
        value: gitlab.lnu.se:5050/2dv013/student/team-2024-04-snorlax/litter-mono/staging-frontend
      - op: add
        path: /manifests/rawYaml/1/spec/ingressClassName
        value: nginx