apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: litter-web-app
build:
  artifacts:
    - image: frontend
      docker:
        dockerfile: Dockerfile.production
      context: ./frontend
manifests:
  rawYaml:  # Use raw yaml for local dev
    - frontend/k8s/base/litter.yaml
    - frontend/k8s/base/ingress.production.yaml
deploy:
  kubectl: {}

profiles:
  - name: production
    manifests:
      kustomize:
        paths:
          - k8s/overlays/production  # Points to central overlay

  - name: staging
    manifests:
      kustomize:
        paths: 
          - k8s/overlays/staging