apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: litter-web-app
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: frontend
      context: ./frontend
      docker:
        dockerfile: Dockerfile.production
    - image: write-service
      context: ./write-service
      docker:
        dockerfile: Dockerfile.production
    - image: api-gateway
      context: ./api-gateway
      docker:
        dockerfile: Dockerfile.production
manifests:
  rawYaml:
    # NOTE - Frontend deployments 
    - ./frontend/k8s/ingress.yaml
    - ./frontend/k8s/litter.yaml
    # NOTE - Message Broker deployments
    - ./message-broker/k8s/strimzi-kafka-zookeeper.yaml
    - ./message-broker/k8s/test-topic.yaml
    - ./message-broker/k8s/kafka-ui.yaml
    - ./message-broker/k8s/user-registration-topic.yaml
    # NOTE - Write Service
    - ./write-service/k8s/write-service.yaml
    - ./write-service/k8s/write-db.yaml
    # NOTE - Gateway Service
    - ./api-gateway/k8s/api-gateway.yaml
deploy:
  kubectl: {}

profiles:
  - name: production
    patches:
      - op: replace
        path: /manifests/rawYaml/0
        value: ./frontend/k8s/ingress.production.yaml
      - op: replace
        path: /manifests/rawYaml/6
        value: ./write-service/k8s/write-service.prod.yaml
      - op: replace
        path: /manifests/rawYaml/7
        value: ./write-service/k8s/write-db.prod.yaml
      - op: remove
        path: /manifests/rawYaml/4
