apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: litter-web-app
build:
  artifacts:
    - image: frontend
      context: ./frontend
      docker:
        dockerfile: Dockerfile.production
manifests:
  rawYaml:
    # NOTE - Frontend deployments 
    - ./frontend/k8s/ingress.yaml
    - ./frontend/k8s/litter.yaml
    # NOTE - Message Broker deployments
    - ./message-broker/k8s/strimzi-kafka-zookeeper.yaml
    - ./message-broker/k8s/test-topic.yaml
deploy:
  kubectl: {}

profiles:
  - name: production
    patches:
      - op: replace
        path: /manifests/rawYaml/0
        value: ./frontend/k8s/ingress.production.yaml
