apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: ${NAMESPACE}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "${DOCKER_SERVER}": {
          "username": "${DOCKER_USERNAME}",
          "password": "${DOCKER_PASSWORD}",
          "email": "${DOCKER_EMAIL}"
        }
      }
    }