apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: ${NAMESPACE}
type: Opaque
stringData:
  docker-server: "${DOCKER_SERVER}"
  docker-username: "${DOCKER_USERNAME}"
  docker-password: "${DOCKER_PASSWORD}"
  docker-email: "${DOCKER_EMAIL}"