apiVersion: v1
kind: Secret
metadata:
 name: service-dns-secrets
type: Opaque
stringData:
 USER_SERVICE_URL: ${USER_SERVICE_URL}
 POST_SERVICE_URL: ${POST_SERVICE_URL}
 WRITE_SERVICE_URL: ${WRITE_SERVICE_URL}
 API_GATEWAY_URL: ${API_GATEWAY_URL}