apiVersion: v1
kind: Service
metadata:
  labels:
    service.name: write-service
  name: write-service
spec:
  ports:
    - name: "write-service-port"
      port: 8888
      targetPort: "write-svc-http"
  selector:
    deployment.name: write-service
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: write-service
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment.name: write-service
  template:
    metadata:
      labels:
        deployment.name: write-service
    spec:
      containers:
      - name: write-service
        image:  write-service # NOTE - This is base one for dev, the "real one" is set in pipeline
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "100m"
        env:
        - name: PORT
          value: "5000"
        - name: WRITE_DB_CONNECTION_STRING
          value: "mongodb://write-db-0.write-db-headless:27017"
        - name: MESSAGE_BROKER_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: kafka-connection
              key: MESSAGE_BROKER_CONNECTION_STRING
        - name: USER_REGISTER_TOPIC
          valueFrom:
            secretKeyRef:
              name: topic-names
              key: USER_REGISTER_TOPIC
        - name: NEW_POST_TOPIC
          valueFrom:
            secretKeyRef:
              name: topic-names
              key: NEW_POST_TOPIC
        - name: DELETE_POST_TOPIC
          valueFrom:
            secretKeyRef:
              name: topic-names
              key: DELETE_POST_TOPIC
        ports:
          - containerPort: 5000
            name: write-svc-http
      imagePullSecrets:
      - name: regcred