apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-kafka-cluster
  annotations:
    # This ensures the operator CRDs are available before creating this resource
    "helm.sh/hook-weight": "1"
    "kubectl.kubernetes.io/wait": "true"
    # Wait for the operator deployment to be ready
    "kubectl.kubernetes.io/wait-for": "condition=Available apiVersion=apps/v1 kind=Deployment name=strimzi-cluster-operator-v0.31.1 namespace=default"
spec:
  kafka:
    version: 3.2.3
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: external
        port: 29092
        type: nodeport
        tls: false
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
    # TODO - Might need to lower these...
    resources:
      limits:
        memory: "1Gi"     
        cpu: "1000m"      
      requests:
        memory: "512Mi"   
        cpu: "500m"       
    storage:
      type: ephemeral

  zookeeper:
    replicas: 1
    resources:
      limits:
        memory: "512Mi"   
        cpu: "500m"     
      requests:
        memory: "256Mi"
        cpu: "250m"
    storage:
      type: ephemeral