apiVersion: v1
kind: Namespace
metadata:
  name: ingress-system
---
# Then place the Ingress in that namespace
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: ingress-system
spec:
  rules:
    - http:
        paths:
          - path: /staging(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: litter-staging
                port:
                  number: 8888
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: litter-production
                port:
                  number: 8888